:source-highlighter: highlightjs

= 2. Spring Bootチュートリアル

元記事は外部からアクセス不可のため、リンクは省略する。

元記事と異なり、IntelliJ IDEA Ultimate 2021.1.1で取り組んだ。 +
また、ビルドスクリプトにはGradleを採用した。

---

=== 1. 環境構築

*■ 1. プロジェクトの生成*

https://start.spring.io/[Spring Initializr]を用いてプロジェクトを準備する。 +
ProjectではGradle Projectを選択する。

zipをダウンロードしたら、Gitで管理しているリポジトリ直下に展開し、IntelliJでオープンする。 +
Gradle Scriptが見つかった旨のポップアップが表示されたら、importを選択し、Trust Projectを押下する。 +

*■ 2. 実行可能にする*

TutorialApplication.javaを開くと、JDKを選択するように促されるため、Java 11(または8)のJDKを選択する。

その後、「View」⇒「Tool Windows」⇒「Gradle」を選択し、buildタスク、bootRunタスクを順に実行する。 +
bootRunタスクがExecuting 80％になったら、以下のURLにアクセスし、404エラーが表示されることを確認する。

http://localhost:8080/

=== 2. 実装

元記事をもとに実装する。
その他の注意点や、元記事から変更した箇所を補足する。

*■ 1.依存関係の追加*

Spring Boot ver 2.3以降の場合、spring-boot-starter-webにjavax.validationが含まれなくなったため、依存関係をビルドスクリプトに追加する必要がある。

[source,groovy]
----
implementation group: 'javax.validation', name: 'validation-api', version: '2.0.1.Final'
----

*■ 2.テストの自動生成*

テスト対象のクラスで右クリックし、「Generate」⇒「Test」を選択することで、テストクラスの雛型を自動生成できる。

*■ 3.REST Clientについて*

元記事で採用されているTalend API Testerは起動できなかったため、Advanced REST Clientを用いて動作確認を実施した。

*■ 4.警告への対応*

・フィールドインジェクトをコンストラクタインジェクトに置き換えた。

・SQLファイルを編集すると以下の警告が出るため対処した。 +
　- No data sources are configured to run this sql... +
　　⇒ローカルのデータソースとしてH2を設定した。 +
　
　- Sql dialect is not configured +
　　⇒File→Settings→Languages＆Frameworks→SQL Dialectsで、Project SQL DialectsにH2を指定した。

・テストクラスで以下の警告が発生していたため対処した。 +
　- TodoRepositoryTest#testFindByID()で'Optional.get()' without 'isPresent()' check +
　　⇒Optional#isPresent()メソッドによるチェックを追加した。 +
　
　- assertThat(foo).isEqualToComparingFieldByField(bar); が非推奨機能になっている。 +
　　⇒assertThat(foo).usingRecursiveComparison().isEqualTo(bar);に置き換える。 +
　
　- assertThat(foo).isEqualToIgnoringGivenFields(bar, baz).hasNoNullFieldsOrProperties(); が非推奨機能になっている。 +
　　⇒assertThat(foo).usingRecursiveComparison().ignoringFields(baz).isEqualTo(bar); +
　　　assertThat(foo).hasNoNullFieldsOrProperties();に置き換える。
　
　- assertThat(foo).isEqualToComparingOnlyGivenFields(bar, baz).hasFieldOrPropertyWithValue(x, y); が非推奨機能になっている。 +
　　⇒assertThat(foo).usingRecursiveComparison().ignoringFields(baz以外の全てのメンバを列挙).isEqualTo(bar); +
    　　　assertThat(foo).hasFieldOrPropertyWithValue(x, y);に置き換える。 +
    　　⇒*より良い方法があるかどうか確認したい。*


*■ 4.その他の質問事項*

・TodoRepositoryTest#testUpdateById()が通らない。 +
　⇒todoの状態が更新されるため。通らないのが正しい？

・MochitoのwillDoNothing()の使い所、目的について理解したい。